export const CART_ADD_REQUEST = "CART_ADD_REQUEST"
export const CART_ADD_SUCCESS = "CART_ADD_SUCCESS"
export const CART_ADD_FAIL = "CART_ADD_FAIL"

export const CART_GET_REQUEST = "CART_GET_REQUEST"
export const CART_GET_SUCCESS = "CART_GET_SUCCESS"
export const CART_GET_FAIL = "CART_GET_FAIL"

export const CART_ITEM_REMOVE_REQUEST = "CART_ITEM_REMOVE_REQUEST"
export const CART_ITEM_REMOVE_SUCCESS = "CART_ITEM_REMOVE_SUCCESS"
export const CART_ITEM_REMOVE_FAIL = "CART_ITEM_REMOVE_FAIL"

export const CART_ITEM_UPDATE_REQUEST = "CART_ITEM_UPDATE_REQUEST"
export const CART_ITEM_UPDATE_SUCCESS = "CART_ITEM_UPDATE_SUCCESS"
export const CART_ITEM_UPDATE_FAIL = "CART_ITEM_UPDATE_FAIL"
