export const SHIPPING_ADD_ADD_REQUEST = "SHIPPING_ADD_ADD_REQUEST"
export const SHIPPING_ADD_ADD_SUCCESS = "SHIPPING_ADD_ADD_SUCCESS"
export const SHIPPING_ADD_ADD_FAIL = "SHIPPING_ADD_ADD_FAIL"

export const SHIPPING_ADD_GET_REQUEST = "SHIPPING_ADD_GET_REQUEST"
export const SHIPPING_ADD_GET_SUCCESS = "SHIPPING_ADD_GET_SUCCESS"
export const SHIPPING_ADD_GET_FAIL = "SHIPPING_ADD_GET_FAIL"

export const SHIPPING_ADD_REMOVE_REQUEST = "SHIPPING_ADD_REMOVE_REQUEST"
export const SHIPPING_ADD_REMOVE_SUCCESS = "SHIPPING_ADD_REMOVE_SUCCESS"
export const SHIPPING_ADD_REMOVE_FAIL = "SHIPPING_ADD_REMOVE_FAIL"

export const SHIPPING_ADD_UPDATE_REQUEST = "SHIPPING_ADD_UPDATE_REQUEST"
export const SHIPPING_ADD_UPDATE_SUCCESS = "SHIPPING_ADD_UPDATE_SUCCESS"
export const SHIPPING_ADD_UPDATE_FAIL = "SHIPPING_ADD_UPDATE_FAIL"
